swagger: "2.0"
info:
  title: beego Test API
  description: beego has a very cool tools to autogenerate documents for your API
  version: 1.0.0
  termsOfService: http://beego.me/
  contact:
    email: astaxie@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
basePath: /v1
paths:
  /consecutivo/:
    get:
      tags:
      - consecutivo
      description: get Consecutivo
      operationId: ConsecutivoController.Get All
      parameters:
      - in: query
        name: query
        description: Filter. e.g. col1:v1,col2:v2 ...
        type: string
      - in: query
        name: fields
        description: Fields returned. e.g. col1,col2 ...
        type: string
      - in: query
        name: sortby
        description: Sorted-by fields. e.g. col1,col2 ...
        type: string
      - in: query
        name: order
        description: Order corresponding to each sortby field, if single value, apply to all sortby fields. e.g. desc,asc ...
        type: string
      - in: query
        name: limit
        description: Limit the size of result set. Must be an integer
        type: string
      - in: query
        name: offset
        description: Start position of result set. Must be an integer
        type: string
      responses:
        "200":
          description: ""
          schema:
            type: array
            items:
              $ref: '#/definitions/models.Consecutivo'
        "404":
          description: not found resource
    post:
      tags:
      - consecutivo
      description: create Consecutivo
      operationId: ConsecutivoController.Post
      parameters:
      - in: body
        name: body
        description: body for Consecutivo content
        required: true
        schema:
          $ref: '#/definitions/models.Consecutivo'
      responses:
        "201":
          description: '{int} models.Consecutivo'
        "400":
          description: the request contains incorrect syntax
  /consecutivo/{id}:
    get:
      tags:
      - consecutivo
      description: get Consecutivo by id
      operationId: ConsecutivoController.Get One
      parameters:
      - in: path
        name: id
        description: The key for staticblock
        required: true
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.Consecutivo'
        "404":
          description: not found resource
definitions:
  models.Consecutivo:
    title: Consecutivo
    type: object
    properties:
      Activo:
        type: boolean
      Consecutivo:
        type: integer
        format: int64
      ContextoId:
        type: integer
        format: int64
      Descripcion:
        type: string
      FechaCreacion:
        type: string
      FechaModificacion:
        type: string
      Id:
        type: integer
        format: int64
      Year:
        type: number
        format: double
tags:
- name: consecutivo
  description: |
    ConsecutivoController operations for Consecutivo
